// This file is auto-generated by scripts/fetchPermissionFromDb.ts
// Do not edit this file manually.

type PermissionConfigShape = {
  readonly id: string;
  readonly resource: string;
  readonly action: string;
  readonly menu: { readonly id: string; readonly title: string; readonly path?: string | null } | null;
};

export const permissionsConfig = [
  {
    "id": "pe_r9OA3piAEX",
    "resource": "aa",
    "action": "aaa",
    "menu": {
      "id": "wUDWmFoS2J",
      "title": "Page",
      "path": "/article"
    }
  },
  {
    "id": "pe_AvKjqrDXPO",
    "resource": "rw",
    "action": "re",
    "menu": {
      "id": "tUkCKz1yfd",
      "title": "Navigation",
      "path": "/navigation"
    }
  },
  {
    "id": "pe_FL7RookSEh",
    "resource": "vv",
    "action": "bb",
    "menu": {
      "id": "wUDWmFoS2J",
      "title": "Page",
      "path": "/article"
    }
  },
  {
    "id": "pe_aA2JP4B4Xm",
    "resource": "cc",
    "action": "cc",
    "menu": {
      "id": "JiZgDz80U6",
      "title": "Team",
      "path": "/team"
    }
  }
] as const satisfies readonly PermissionConfigShape[];

export type PermissionResource = (typeof permissionsConfig)[number]['resource'];
export type PermissionAction = (typeof permissionsConfig)[number]['action'];
