// This file is auto-generated by scripts/fetchPermissionFromDb.ts
// Do not edit this file manually.

type PermissionConfigShape = {
  readonly id: string;
  readonly resource: string;
  readonly action: string;
  readonly menu?: { readonly id: string; readonly title: string; readonly path?: string | null } | null;
};

export const permissionsConfig = [
  {
    "id": "pe_7tb7zg9lo7",
    "resource": "member",
    "action": "edit",
    "menu": {
      "id": "JiZgDz80U6",
      "title": "Team",
      "path": "/team"
    }
  },
  {
    "id": "pe_mCRXwVcqvv",
    "resource": "member",
    "action": "view",
    "menu": {
      "id": "JiZgDz80U6",
      "title": "Team",
      "path": "/team"
    }
  }
] as const satisfies readonly PermissionConfigShape[];

export type PermissionResource = (typeof permissionsConfig)[number]['resource'];
export type PermissionAction = (typeof permissionsConfig)[number]['action'];
